DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER(
	ID INT PRIMARY KEY, 
	NAME VARCHAR(255),
	SURNAME VARCHAR(255)
);
/*TOP 15 BASKETBALL PLAYER*/
INSERT INTO CUSTOMER VALUES(1, 'Lebron','James');
INSERT INTO CUSTOMER VALUES(2, 'Sthephen','Curry');
INSERT INTO CUSTOMER VALUES(3, 'Michael','Jordan');
INSERT INTO CUSTOMER VALUES(4, 'Kobe','Bryant');
INSERT INTO CUSTOMER VALUES(5, 'Kevin','Durant');
INSERT INTO CUSTOMER VALUES(6, 'James','Harden');
INSERT INTO CUSTOMER VALUES(7, 'Magic','Jhohnson');
INSERT INTO CUSTOMER VALUES(8, 'Kerim Abdul','Cabbar');
INSERT INTO CUSTOMER VALUES(9, 'Bill','Russell');
INSERT INTO CUSTOMER VALUES(10, 'Kawhi','Leonard');
INSERT INTO CUSTOMER VALUES(11, 'Oscar','Robertson');
INSERT INTO CUSTOMER VALUES(12, 'Tim','Duncan');
INSERT INTO CUSTOMER VALUES(13, 'Scottie','Pippen');
INSERT INTO CUSTOMER VALUES(14, 'Anthony','Davis');
INSERT INTO CUSTOMER VALUES(15, 'Haleem','Olajuwon');

